fail smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -305,10 +305,55 @@ jobs:
       - slack/notify:
           event: fail
           template: basic_fail_1
-      # - destroy-environments:
-      #     workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      # - revert-migrations:
-      #     workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"                               
+      - destroy-environments:
+          workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"  
+      - revert-migrations:
+          workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"  
+  smoke-test:
+    docker:
+      - image: python:3.9-alpine3.16 
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl jq tar gzip
+            pip install awscli
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            API_URL="http://${BACKEND_IP}:3030/api/status"
+            echo ${API_URL}
+            if curl -s $API_URL | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL}
+            if curl --insecure -s ${URL} | grep "Welcome"
+            then
+              return 1
+            else
+              return 1
+            fi  
+      # Here's where you will add some code to rollback on failure
+      - slack/notify:
+          event: fail
+          template: basic_fail_1
+      - destroy-environments:
+          workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"  
+      - revert-migrations:
+          workflowId: "${CIRCLE_WORKFLOW_ID:0:7}"
+
 workflows:
   default:
     jobs:
@@ -332,3 +377,5 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
